language: emacs-lisp
sudo: true
env:
  matrix:
    - EMACS=emacs24        EMACS_PPA=ppa:cassou/emacs
    - EMACS=emacs-snapshot EMACS_PPA=ppa:ubuntu-elisp/ppa
  global:
    - GH_REPO: github.com/coldnew/coldnew-emacs.git
    - secure: EysgSkwXLavPxWUwBjs33DtXfVL9999pPq3riAsUJaSOuMzBHBypNsZAgpZHuu+oIaw819MX0+sPxIAFQhcBNqe19aqMJqR5N7Q5Q97AUSIMDfKyIbkA/iUcSx5nTMSjejjocvrCqAYlSSbitfjUB0jw08EIq5HeVxtWst4+p8M=
notifications:
  email: false
branches:
  only:
    - master
before_install:
  - sudo add-apt-repository -y "$EMACS_PPA"
  - sudo apt-get update -qq
  - sudo apt-get install --force-yes -qq "$EMACS"
  - sudo apt-get install --force-yes -qq "${EMACS}-el" || true
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="${HOME}/.cask/bin:$PATH"
install:
  - '"$EMACS" --version'
script:
  - rm -rf .cask/
  - make clean
  - make bootstrap
  - make init.html
  - make init.el.html

after_success:
  - ./scripts/deploy-gh-pages.sh
